version: '3.7'

services:
    api:
        build:
            context: ./api
        container_name: api
        ports:
             - "5000:1707"
    bot:
        build:
            context: ./bot
        container_name: bot
        depends_on:
             - api 

